#!/usr/bin/env ruby
# frozen_string_literal: true

require "bundler/setup"
require "magic_bus"
cmd = "shoryuken -q #{MagicBus.sqs_queue} -r #{File.expand_path("../lib/magic_bus/worker.rb", __dir__)} -R"
puts cmd
system(cmd)
